/**
 * 气候变化影响评估 — 适应策略预设
 */

import type { AdaptationStrategy } from './climateTypes';

export const ADAPTATION_STRATEGIES: AdaptationStrategy[] = [
  {
    id: 'AS01',
    category: 'supply',
    name: '多水源联合调配',
    description: '地表水-地下水-外调水-再生水联合调度，降低单一水源依赖',
    applicableScenario: ['rcp45', 'rcp85', 'ssp245', 'ssp585'],
    priority: 'high',
    implementationTime: 'medium',
    cost: 'high',
    expectedBenefit: '供水保障率提升15-25%，地下水开采量减少20%',
  },
  {
    id: 'AS02',
    category: 'supply',
    name: '人工补给( MAR)',
    description: '利用雨洪水和再生水进行地下水人工补给，恢复超采区水位',
    applicableScenario: ['rcp45', 'rcp85', 'ssp245', 'ssp585'],
    priority: 'high',
    implementationTime: 'medium',
    cost: 'medium',
    expectedBenefit: '年补给量增加500-2000万m³，水位回升0.5-2m/a',
  },
  {
    id: 'AS03',
    category: 'demand',
    name: '节水型社会建设',
    description: '农业高效节水灌溉+工业循环利用+生活节水器具推广',
    applicableScenario: ['rcp45', 'rcp85', 'ssp245', 'ssp585'],
    priority: 'high',
    implementationTime: 'short',
    cost: 'low',
    expectedBenefit: '用水总量降低15-30%，灌溉水利用系数提升至0.7+',
  },
  {
    id: 'AS04',
    category: 'demand',
    name: '种植结构调整',
    description: '推广耐旱作物品种，减少高耗水作物种植面积',
    applicableScenario: ['rcp85', 'ssp585'],
    priority: 'medium',
    implementationTime: 'short',
    cost: 'low',
    expectedBenefit: '农业用水减少10-20%，抗旱能力增强',
  },
  {
    id: 'AS05',
    category: 'ecology',
    name: '生态补水保障',
    description: '保障河流基流和湿地生态需水，维护地下水依赖生态系统',
    applicableScenario: ['rcp45', 'rcp85', 'ssp245', 'ssp585'],
    priority: 'high',
    implementationTime: 'medium',
    cost: 'medium',
    expectedBenefit: '生态基流保证率达90%，GDE面积稳定或恢复',
  },
  {
    id: 'AS06',
    category: 'ecology',
    name: '河岸带恢复',
    description: '恢复河岸带植被缓冲区，增强自然补给和净化功能',
    applicableScenario: ['rcp45', 'ssp245'],
    priority: 'medium',
    implementationTime: 'long',
    cost: 'medium',
    expectedBenefit: '河岸带补给量增加5-15%，水质净化能力提升',
  },
  {
    id: 'AS07',
    category: 'monitoring',
    name: '气候-地下水耦合监测网',
    description: '建设气候变化与地下水响应的长期监测预警网络',
    applicableScenario: ['rcp45', 'rcp85', 'ssp245', 'ssp585'],
    priority: 'high',
    implementationTime: 'short',
    cost: 'low',
    expectedBenefit: '预警提前量3-6个月，决策响应速度提升50%',
  },
  {
    id: 'AS08',
    category: 'monitoring',
    name: '干旱风险预警系统',
    description: '基于SPI/SPEI的干旱监测预警+地下水响应模型',
    applicableScenario: ['rcp85', 'ssp585'],
    priority: 'high',
    implementationTime: 'short',
    cost: 'low',
    expectedBenefit: '干旱响应时间缩短50%，应急供水效率提升',
  },
  {
    id: 'AS09',
    category: 'governance',
    name: '动态水权分配',
    description: '根据气候预测和水资源状况动态调整取水许可',
    applicableScenario: ['rcp45', 'rcp85', 'ssp245', 'ssp585'],
    priority: 'medium',
    implementationTime: 'medium',
    cost: 'low',
    expectedBenefit: '水资源配置效率提升20%，超采控制力度增强',
  },
  {
    id: 'AS10',
    category: 'governance',
    name: '地下水-地表水联合管理',
    description: '统一规划管理地表水和地下水资源，实施联合调度',
    applicableScenario: ['rcp45', 'rcp85', 'ssp245', 'ssp585'],
    priority: 'high',
    implementationTime: 'long',
    cost: 'medium',
    expectedBenefit: '水资源利用效率提升15-25%，系统抗风险能力增强',
  },
];

// ── 6. 综合评估 ──

